apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      error_page 404 = @custom_404;

      location @custom_404 {
        return 302 https://www.google.com;
      }
spec:
  rules:
  - host: app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
