apiVersion: ENC[AES256_GCM,data:s6Y=,iv:0TtKV+V3XzxIIpTshPXMsaNARVSjo0X3aYVH26HSZfE=,tag:uxtXEI2oqSUByxst8q2tgA==,type:str]
kind: ENC[AES256_GCM,data:nK7T8Y/c,iv:QY+OwqmBZwfycfHHH6cb/CesPXrgA+fY+IMu34Hkbhs=,tag:qNXPiwWTTF3F8fxB8A4F4A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Hva125mI2/ombmkZ,iv:EPkB4WBUFqSNGji41PCCtuBRzzG7eZq+tYfP4BbpSsU=,tag:8OJlP9KFY3OeV8vuUn3Y/g==,type:str]
    namespace: ENC[AES256_GCM,data:0HSzZnL3ow==,iv:MtaVFsbAdSWs73/Ll+c+IoexI3zExIUZbbMQoIyRL/k=,tag:qhyI5vZ6FNVSEZTtNtQ7bw==,type:str]
type: ENC[AES256_GCM,data:2QoD8srW,iv:N0WOqcYG104DbwPALpROPcnxWHkDCYTProC+vrUH2h8=,tag:I0u9KukkW4aqu7Pi1NEFyA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:+VKpjDQ+,iv:YyStcbqIPferLY3nQUxlTwd9LAAVf7pYIewttmSN8Qc=,tag:lUwGfYedbu4e8OBV/yxLeQ==,type:str]
    password: ENC[AES256_GCM,data:v7sWzTCUkAenSJJE4h4rBcWNYP2t4LPYLN4=,iv:jgQNBRXP1CuE94Cwqx/UNNTWByVcTop1b/2cYC+SgTk=,tag:gvtak2iYiDvYLVI8CBz9AQ==,type:str]
sops:
    age:
        - recipient: age1qdc4lfungzxtldtwrmu98twelw3avkq0sgf6um3m2jmtnw7w4d3qqauv38
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYmhBL2hNeWhzUWM2ZHYw
            UkxmT1N4ai95V1dtN0lJa2k5dXZ2T3hoZ1hZClBCMVFKWFl1ZGY4Z29yMUlsN1li
            QmRKOWx1N1lSL2RmNllVaW4zVFAzREUKLS0tIDd6cDlOWUFXcHVJMkJaZmdjSlNu
            c3VFZGVaeCtqeUxqbXNpTGRnMnlhdjQKp/7aoxnWb6hb1NiKmHmQ8qdYQq6QWCVP
            1BDeVEVZTGs1rYUZlZ1qgFobud0ydOctSHIe9s0lLcK6NBCmcsnXkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T10:57:45Z"
    mac: ENC[AES256_GCM,data:UE4/sVd10o+fFUqMg9yw8QSTrBti2n+HlYFE0yXoByL1HgoPkFRiJncY3Ciz1uiEFCkSHOo+RNjJxAtHVgOTfKoycBR/E+gN6eyc5Pk6OdgL2F3l8g1sRvm43ZEZKepQqBsoXD05snS3zoL4TYKJ4rNI2hRisVrUJoTblj7g7Jw=,iv:wJ75soCW3PrC/2iktd+o3VPnYmsFMltpYxWN9+WVfIo=,tag:b2OZvTWel0KP1ZBImQjVwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
