apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-k3s
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/my-k3s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
  resources:
    - ./flux-system
    - ./infrastructure/metallb
    - ./infrastructure/ingress-nginx
    - ./apps/base/mysql
    - ./apps/base/wordpress
