apiVersion: ENC[AES256_GCM,data:wds=,iv:SZvuUHM2cQR8FP6X/HeeveZs8zzIBrIm7jBVytFSU4s=,tag:Buqg84TznIBkHf26SC3A3Q==,type:str]
kind: ENC[AES256_GCM,data:N12gywnI,iv:Y+mgS8IPaYIco4x/y0aRLRlNMi9+O6g5IJO6+DupxLo=,tag:MBhOLqq8JmKVBaELkGbBZw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:omUTeTyM/loFGlUY,iv:EwXlMGekD8QPbG6NEqSCwU70GaeDYAO2SlTT16Lt+Cg=,tag:7UfBDLzIpPpRTinKPnVXFw==,type:str]
    namespace: ENC[AES256_GCM,data:Q1tBVF/x1g==,iv:9YzSVOuRyCIA88YAzNWay5mYtE9nm6CjH5ikGD+Q34Q=,tag:wYz/osZxwBfHiFWXll8spg==,type:str]
type: ENC[AES256_GCM,data:E0YMDR6t,iv:DZDuwKeQspOXvmyOQudv+1aJ/pi5mNWwt/cQVd7hN8U=,tag:niDjXWyGxYeNPU35KtAMiQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:3zNTca+F,iv:JurGtMBux8mcqLEXsYAv3157st06Wn29zVh2MHnlKkI=,tag:ibozmhRk36zUQmR055G7sg==,type:str]
    password: ENC[AES256_GCM,data:+WrJ122C,iv:MN9qDD8Uw5hIGHUTathYFAVahfi3bJiUZiRDbC7aFHE=,tag:aoINi4shjDVB1ePN0mbdcw==,type:str]
sops:
    age:
        - recipient: age18ylr9sfw0cj8k3cts6w9caxhl0hrnnwta6czswdjjjmve6c9yffsgjwsyu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENC9hN2dESUNHdlAwekg3
            VjBUSHdyQUdXKzJLSVYwMFpVM2ExazdjMkNZCm5KQjJHMGtSVXNRY0wyU2FYQzJq
            bGsrU2pHWkczSnhoNEc5b0diazNSMzQKLS0tIFZRdGFiWVZZMUE1YUFKMjd3VS90
            M3JRTFRRc1hQTHYrb1hBc3JnRlhlNVUKwtDyzCHaZD4bsIUUNAIB2DTda5ds/f02
            gFKCI9vzq8UNApOBSFx1uNSG3xzbxoYjmU94Za6jiuRK28HPUuhuiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T05:53:19Z"
    mac: ENC[AES256_GCM,data:9Qho2sesdD/bDnlXX0B+LN5ZZLWryVWgOsm6RhLioM3Myc7BMOW5BVJEmQKwX/DFs7UwYPsxMaDa8WsAKCm6UZbGp/KcbGIGoCUiarPdEsMIskwtU0CNKdSHc0KiTvk2s3gT6XMVNOFoJaQQ01LMJCbpshtjx6S60uGZkfvj174=,iv:QQCxeIWCiziam/zwdS8HxB9OMFVquIqNP39KkEClTWY=,tag:NBzA13/vsyZ0ryZ2ZG9LVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
