apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
   controller:
    service:
      type: LoadBalancer
    config:
      # tell ingress-nginx to use Lua dynamic modules
      lua-shared-dicts: "cache:10m"
      lua-resty-redirect-404: "true"
    extraVolumes:
      - name: lua-redirect-404
        configMap:
          name: lua-redirect-404
    extraVolumeMounts:
      - name: lua-redirect-404
        mountPath: /etc/nginx/lua
        readOnly: true
    # Inject Lua hook into nginx.conf
    server-snippet: |
      error_page 404 = @custom_404;

      location @custom_404 {
        default_type text/html;
        content_by_lua_block {
          local redirect = require("redirect")
          redirect.handle_404()
        }
      }
