apiVersion: v1
kind: ConfigMap
metadata:
  name: lua-redirect-404
  namespace: ingress-nginx
data:
  redirect.lua: |
    function handle_404()
      ngx.status = 302
      ngx.header["Location"] = "https://www.google.com"
      return ngx.exit(302)
    end
