apiVersion: v1
kind: ConfigMap
metadata:
  name: lua-redirect-404
  namespace: ingress-nginx
data:
  redirect_404.lua: |
    local _M = {}

    function _M.header_filter()
      if ngx.status == 404 then
        ngx.status = 302
        ngx.header["Location"] = "https://www.google.com"
        ngx.header["Cache-Control"] = "no-cache"
      end
    end

    return _M

