apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-404-plugin
  namespace: ingress-nginx
data:
  main.lua: |
    local _M = {}

    function _M.rewrite()
      if ngx.status == 404 then
        return ngx.redirect("https://google.com", 302)
      end
    end

    return _M
